%{?!ros_distro:%global ros_distro rolling}
%global pkg_name smach_ros
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-smach-ros
Version:        3.0.3
Release:        2%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
The smach_ros package contains extensions for the SMACH library to integrate it
tightly with ROS. For example, SMACH-ROS can call ROS services, listen to ROS
topics, and integrate with actionlib both as a client, and a provider of action
servers. SMACH is a new library that takes advantage of very old concepts in
order to quickly create robust robot behavior with maintainable and modular
code.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
The smach_ros package contains extensions for the SMACH library to integrate it
tightly with ROS. For example, SMACH-ROS can call ROS services, listen to ROS
topics, and integrate with actionlib both as a client, and a provider of action
servers. SMACH is a new library that takes advantage of very old concepts in
order to quickly create robust robot behavior with maintainable and modular
code.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
The smach_ros package contains extensions for the SMACH library to integrate it
tightly with ROS. For example, SMACH-ROS can call ROS services, listen to ROS
topics, and integrate with actionlib both as a client, and a provider of action
servers. SMACH is a new library that takes advantage of very old concepts in
order to quickly create robust robot behavior with maintainable and modular
code.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Tue Apr 21 2026 Isaac I. Y. Saito <gm130s@gmail.com> - 3.0.3-2
- Autogenerated by Bloom
