%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name smach
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-smach
Version:        3.0.3
Release:        4%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
SMACH is a task-level architecture for rapidly creating complex robot behavior.
At its core, SMACH is a ROS-independent Python library to build hierarchical
state machines. SMACH is a new library that takes advantage of very old concepts
in order to quickly create robust robot behavior with maintainable and modular
code.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
SMACH is a task-level architecture for rapidly creating complex robot behavior.
At its core, SMACH is a ROS-independent Python library to build hierarchical
state machines. SMACH is a new library that takes advantage of very old concepts
in order to quickly create robust robot behavior with maintainable and modular
code.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
SMACH is a task-level architecture for rapidly creating complex robot behavior.
At its core, SMACH is a ROS-independent Python library to build hierarchical
state machines. SMACH is a new library that takes advantage of very old concepts
in order to quickly create robust robot behavior with maintainable and modular
code.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Wed Apr 29 2026 Isaac Saito <iisaac.saito@gmail.com> - 3.0.3-4
- Autogenerated by Bloom

* Tue Apr 28 2026 Isaac Saito <iisaac.saito@gmail.com> - 3.0.3-3
- Autogenerated by Bloom

* Tue Apr 21 2026 Isaac Saito <iisaac.saito@gmail.com> - 3.0.3-2
- Autogenerated by Bloom
